### ISSUE TITLE
feat(no-path-verbs): inspect api paths for verbs 

### ISSUE THREAD

**Issue by gregswindle** [gregswindle/eslint-plugin-swagger-tools#3]
## User story

As an API engineer or architect,
I need to ensure that APIs conform to style guidelines
In order to promote and foster a consistent suite of services.

## Acceptance criteria

- [x] 1. Common English verbs are identified in Swagger doc path names.

**Comment by gregswindle** [comment]
@stonejoshstone, do you mind replying to this comment with the URL to the whitepaper that evaluated APIs with verbs? I'd like to use its verb prefixes for the `no-path-verb` rule's MVP.

**Comment by gregswindle** [comment]
chore(scm): associated PR #9 merged into `develop`.

Closes #3.

**Comment by stonejoshstone** [comment]
Whitepaper PDF is here:

http://www.springer.com/cda/content/document/cda_downloaddocument/9783319387901-c2.pdf?SGWID=0-0-45-1566419-p179977750
